learning_video:
    resource: "@LearningVideoBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
